### ISSUE TITLE
call function from go

### ISSUE THREAD

**Issue by moisespsena** [skx/monkey#76]
Hello!
How do call function from go?

	env := object.NewEnvironment()
	l := lexer.New(`let add = fn(a, b) { return a + b;}; gofn(add, 2, 3)`)
	p := parser.New(l)

	program := p.ParseProgram()
	if len(p.Errors()) != 0 {
		for _, msg := range p.Errors() {
			fmt.Printf("\t%s\n", msg)
		}
		os.Exit(1)
	}

	evaluator.RegisterBuiltin("gofn",
		func(env *object.Environment, args ...object.Object) object.Object {
			var add = args[0].(*object.Function)
                        
			return add.Invoke(env, args[1:]...) // ?
		})

**Comment by skx** [comment]
Thanks for the question; sadly that isn't possible at the moment:

* monkey can call functions implemented in golang
  * e.g. All the built-in functions.
* golang cannot call back into monkey.
  * You could parse and setup a sub-intepreter, as is done for the `eval` implementation.
  * But that won't help in this case, because the function-object doesnt' contain a copy of its own body.

The evaluator works on AST, and that is private/internal to the evaluator, it _might_ be possible to change the signature of the builtin-functions to add a pointer to the evaluator, but that would require a **huge** overhaul of the internals.  Probably not something I would do.
